### ISSUE TITLE
Please offer Debian + Ubuntu Packages / Repositories

### ISSUE THREAD

**Issue by supersexy** [opendistro-for-elasticsearch/community#10]
Repositories for Debian and Ubuntu Linux Distros would be very useful for people who like to stay secure and do not use rpm based distros and no docker. Thank you very much!

**Comment by elfisher** [comment]
Hi, thanks for the feedback! We've opened a backlog item in [our project](https://github.com/opendistro-for-elasticsearch/community/projects/1) to support this. More news to come soon.

**Comment by satyaakam** [comment]
having a tarball will help all the distros IMHO

**Comment by alolita** [comment]
@satyaakam we're working on providing more types of packages for the distro. Keep a lookout for our upcoming releases.

**Comment by pbuxtonccuk** [comment]
Sooner  rather than later please!! :)

**Comment by ulab** [comment]
There seems to be a documented way to install on Ubuntu or Debian now:

https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/

I am not sure when this was added, but I just stumbled over it :)

**Comment by alolita** [comment]
Hi Everyone! Thanks for your patience! You can now download Debian packages for Open Distro for Elasticsearch version 0.8.0. Download and installation instructions can be found at https://opendistro.github.io/for-elasticsearch/downloads.html 

https://discuss.opendistrocommunity.dev/t/debian-packages-now-available-for-open-distro-for-elasticsearch-0-8-0/448

Please feel free to open issues here on the community repo or on the community forums at https://discuss.opendistrocommunity.dev/c/announcements.
