### ISSUE TITLE
iot_device_simulator Post data to Amazon ElasticSearch failed

### ISSUE THREAD

**Issue by liualexiang** [opendistro-for-elasticsearch/community#107]
I'm using the latest  iot_device_simulator to send data to Amazon ES,

```
python3 main.py -e https://search-myes-qlb7oqmdqwm75k3guoacxxxxxx.us-east-1.es.amazonaws.com
```

However, I always got an 403 error as below
```
[ec2-user@ip-10-0-0-248 iot_device_simulator]$ python3 main.py -e https://search-myes-qlb7oqmdqwm75k3guoacxxxxxx.us-east-1.es.amazonaws.com
Building 10 devices with 5 sensors each and sending 1000 samples to Elasticsearch. Total of 50000 log lines
Flushing documents 1565835606.5986822
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
<Response [403]>
Flushing documents 1565835632.7422068
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
<Response [403]>
```
The certificate warning can be ignored by adding ***requests.packages.urllib3.disable_warnings()***  in transport.py. However, I didn't find a way to solve the 403 issue. Could you please help me on this? thanks.

#### Amazon ES policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:us-east-1:AccountID:domain/myes/*",
      "Condition": {
        "IpAddress": {
          "aws:SourceIp": [
            "The EC2 public which running iot_device_simulator python code"
          ]
        }
      }
    }
  ]
}
```

**Comment by liualexiang** [comment]
Another issue is:  How to specify sensor type when sending data to ES?

**Comment by Jon-AtAWS** [comment]
Thanks for filing the issue. 

I think it's better to have the warnings in there, since really you should use certificate verification and your own certificates, especially in Open Distro for Elasticsearch.

I'm a little mystified by this. Your policy looks OK. Can you dump out and send the error text from the response?

es_line_buffer.py creates _bulk requests with a _type. This won't work for ES 7. It could be that this is somehow causing 403, though I don't know how that would happen.

**Comment by Jon-AtAWS** [comment]
For your second issue, you could add that in the report method of each sensor class.

**Comment by liualexiang** [comment]
Thanks Jon.

The issue was caused by ES authentication part, but not ES version, or ES URI. I finally resolved this issue by remove **auth=('admin', 'admin')** in transport.py.

https://github.com/opendistro-for-elasticsearch/community/compare/master...liualexiang:patch-1
