### ISSUE TITLE
Unable to deploy ES due to issue AWS k8s t3.large

### ISSUE THREAD

**Issue by qafro1** [opendistro-for-elasticsearch/community#115]
When I run the cmd:
kubectl -n elasticsearch get pods

NAME                         READY   STATUS    RESTARTS   AGE
es-master-  xxxx                0/1     Pending               0          31s
es-master-  xxxx               0/1     Pending               0          31s
es-master-  xxxx                0/1     Pending                0          31s

Warning  FailedScheduling  21s (x7 over 3m31s)  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.

Any ideas?

**Comment by chrandal** [comment]
Most likely your NodeAffinity settings. If the NodeAffinity rules are really what you want, try adding more nodes.

**Comment by qafro1** [comment]
Which ES yaml files can I set the NodeAffinity rules to 2 nodes and reduce the JV size to 512M.
So that I can run t3.small?

**Comment by bbarani** [comment]
@qafro1 , You should be able to set it in here - https://github.com/opendistro-for-elasticsearch/community/blob/master/open-distro-elasticsearch-kubernetes/elasticsearch/40-es-master-deploy.yml
