### ISSUE TITLE
Ansible playbook to install Open Distro elasticsearch cluster and kibana using standalone plugin method

### ISSUE THREAD

**Issue by saravanan30erd** [opendistro-for-elasticsearch/community#116]
To make Open Distro standalone plugin installation simple, wrote the ansible playbook which will install and configure Open distro elasticsearch cluster and kibana using standalone method.

Open distro ansible playbook: https://github.com/saravanan30erd/opendistro_standalone_installation

I don't know how to contribute this playbook for other Open Distro users. So added notes and provided pull request to [opendistro documentation](https://github.com/opendistro/for-elasticsearch-docs/pull/126). Please suggest me on how to contribute this playbook.

**Comment by aetter** [comment]
Hey @saravanan30erd, added link here: https://opendistro.github.io/for-elasticsearch-docs/docs/other/

Thanks again!
