### ISSUE TITLE
Flexmonster plugin

### ISSUE THREAD

**Issue by ezuazu** [opendistro-for-elasticsearch/community#120]
Hi, did anyone try to install flexmonster-plugin (https://www.flexmonster.com/blog/new-pivot-table-for-kibana) in the opendistro version?

I was able to install it and the icon appears in Kibana but it is giving me an error when the plugin wants to access elasticsearch.

Thanks in advance.

**Comment by alolita** [comment]
@ezuazu can you also ask this question on the Open Distro discussion forum at https://discuss.opendistrocommunity.dev/c/general-elasticsearch
