### ISSUE TITLE
Percentage on tables

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/community#121]
Hi,

Is there a plan for adding functionalities to Kibana tables? Here are some examples of plugins that are already doing this:

https://github.com/fbaligand/kibana-enhanced-table
https://www.flexmonster.com/blog/new-pivot-table-for-kibana/

Regards

**Comment by dbbaughe** [comment]
Hi @mporracindie,

This seems to be a feature request unrelated to Index Management, going to move it to community repository.

Thanks,
Drew

**Comment by jcgraybill** [comment]
Closing for now. @mporracindie if you're still looking for help, feel free to post a question to the Open Distro forum.
