### ISSUE TITLE
Wazuh app not responding

### ISSUE THREAD

**Issue by Zakaria-Maj** [opendistro-for-elasticsearch/community#124]
Hi Everyone,

**Installation:**

Opendistroforelasticsearch-1.1.0 + Opendistroforelasticsearch-kibana-1.1.0

Wazuh manager-3.10.0 + Wazuh API-3.10.0 + Filebeat-7.3.2 oss

**Issue:**

First i tried to access the wazuh app from the kibana UI, i got an error regarding the index pattern then i fixed it by deleting the .kibana index:

![Screen Shot 2019-09-13 at 10 21 11 AM](https://user-images.githubusercontent.com/44165697/66194090-b13e3f00-e68b-11e9-834a-33b2ec193ba7.png)

After the error is gone, i navigated to the wazuh app to understand how it works but I realized that the function “Discover” is not responding:

![Screen Shot 2019-10-02 at 11 11 57 AM](https://user-images.githubusercontent.com/44165697/66194098-b56a5c80-e68b-11e9-9168-5e9e68cd9d9c.png)

Could anyone help me please?

**Comment by rlk5546** [comment]
Using ODFE 1.1 (ES 7.1.1 and Wazuh 3.9)

**Create new Role**:
    Role: newrolename (this role will augment the kibanaserver role via Roles Mapping)
   - Permissions: 
   -   Index Pattern:  *
     -   Permissions: Single Permissions:
         -   indices:data/read*
         -   indices:data/write*
   -   Index Pattern:  \*wazuh\*
     -   Permissions: Action Groups:
         -   unlimited

**Create new Role Mapping**

- Add New Role Mapping
 - Choose the new role name from the Drop down
   - Add **kibanaserver** as a User

This solved the permissions issues for me.  I also had to manually create the wazuh template for wazuh-alerts-*.

rlk
