### ISSUE TITLE
Pre-package IDE for instant developer onboarding 

### ISSUE THREAD

**Issue by nbon12** [opendistro-for-elasticsearch/community#129]
Hi,

As a developer at All Things Open Hackday, I found it takes hours to get my Mac setup with Yarn, NVM, node, and docker-compose.

It would be faster if there were a 1-click developer ready workspace, for example, see the robotics IDE in Cloud9, that comes pre-installed with all the necessary tools that developers need to get started coding: https://aws.amazon.com/robomaker/

Another example is with [Eclipse Che](https://www.eclipse.org/che/) where all the tools that are needed to begin development on OpenDistro are included so I can save time not having to install all dependencies.

- nvm
- yarn

**Comment by alolita** [comment]
Hi @nbon12 good suggestions. We are looking to integrate Open Distro with various developer workspaces. Stay tuned.
