### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by kfox1111** [opendistro-for-elasticsearch/community#13]
It would be great if there was a helm chart so you could quickly launch opendistro-for-elasticsearch on eks or other Kubernetes clusters.

**Comment by alolita** [comment]
Hi @kfox1111 good suggestion! You're welcome to contribute a Helm chart for Open Distro for Elasticsearch. We're also taking a look at supporting this.

**Comment by raazcrzy** [comment]
Do we have a yaml file for deploying opendistro as a statefulset somewhere?

**Comment by mysticaltech** [comment]
There is a helm chart for the official Elasticsearch, maybe we could piggyback on that one https://github.com/elastic/helm-charts/tree/master/elasticsearch

**Comment by ekirmayer** [comment]
@mysticaltech I didn't get to compare it all but is it a 1:1 in regards to the parameters?

**Comment by gabrielcalderon** [comment]
@ekirmayer Yes, excepto for the TLS settings. Those are more related to SearchGuard.

**Comment by DerekHeldtWerle** [comment]
I've added a PR for this https://github.com/opendistro-for-elasticsearch/community/pull/56 for anyone watching this issue. I did my best to make it as configurable as possible to cater to the individual needs of different setups. If there is something in there that doesn't seem to be supported, feel free to comment on the PR.

**Comment by nixgadget** [comment]
@DerekHeldtWerle happy to test it out. will report back.

**Comment by gauravkohli** [comment]
@nixgadget @DerekHeldtWerle ... any updates on this?

**Comment by waynetaylor** [comment]
Observation here RE the helm chart. I am still new to K8's so learning but i was getting. Master and data nodes pending. After debugging I saw following:

```
kubectl describe pods opendistro-es-1-data-0

Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  43s   default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
```

I apply a storage class to satisfy but this seems missing in the helm package

**Comment by linbingdouzhe** [comment]
yaml build has too many custom setting if upgrade from 0.9.0 to 1.2.0 , it's better to have a helm chart
