### ISSUE TITLE
Unable to index filebeat logs with LogStash

### ISSUE THREAD

**Issue by pkhavkine** [opendistro-for-elasticsearch/community#136]
Hi.

I'm trying to index logs from filebeat with logstash, but I'm getting an from ES:
org.elasticsearch.index.mapper.MapperParsingException: object mapping for [log] tried to parse field [null] as object, but found a concrete value

I am using:
filebeat-7.4.2-1.x86_64
logstash-oss-7.4.2-1.noarch
opendistroforelasticsearch-1.2.1-1.noarch

I imported the filebeat template, but still get the same error.

Thanks

**Comment by jcgraybill** [comment]
Closing for now. @pkhavkine if you're still looking for help, feel free to post a question to the [Open Distro forum](https://discuss.opendistrocommunity.dev/).
