### ISSUE TITLE
OIDC support/documentation

### ISSUE THREAD

**Issue by kfox1111** [opendistro-for-elasticsearch/community#14]
The documentation mentions JWT support, but it is unclear if it is enough to work with OIDC providers and only additional documentation is needed, or if OIDC support would require additional support. Either way, OIDC support would be very useful.

**Comment by elfisher** [comment]
Hi @kfox1111 thanks for the feedback! I'm moving this issue over to our doc repo since it is primarily a documentation issue. Documenting OIDC is in our list. Link to the issue in our docs [here](https://github.com/opendistro/for-elasticsearch-docs/issues/9). Please feel free to give it a 👍thanks!
