### ISSUE TITLE
Snapshot restore fails "no permissions for [ ]..."

### ISSUE THREAD

**Issue by rlk5546** [opendistro-for-elasticsearch/community#152]
ODFE v1.1 (ES7.1.1)

On this page
https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/snapshot-restore/

It says:  
> In order to perform snapshot and restore operations, users must have the built-in manage_snapshots role.

This is not true.

**User Config:** (Trying to keep it simple for now)
Created Role:  "localadmin role" => _cluster:unlimited and indices:*_ permissions.
Created local user:  "localadmin" with _manage_snapshots_ and "_localadmin role_" as backends

Somewhere else I found that this was also required and was already enabled on my cluster:
**elasticsearch.yml:**
`opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
`

Snapshot creation was successful.   Then tested restore after Snapshot creation:
**Command issued in Dev Tools:**
`POST /_snapshot/my_repo/my_snapshot/_restore
{
  "indices": "my_index_to_restore-2019.10.29",
  "ignore_unavailable": true,
  "include_global_state": true
}`

**Response:**
> `{
>   "error": {
>     "root_cause": [
>       {
>         "type": "security_exception",
>         "reason": "no permissions for [] and User [name=localadmin, roles=[manage_snapshots, localadmin role], requestedTenant=__user__]"
>       }
>     ],
>     "type": "security_exception",
>     "reason": "no permissions for [] and User [name=localadmin, roles=[manage_snapshots, localadmin role], requestedTenant=__user__]"
>   },
>   "status": 403
> }`

However.... the same command as a CURL command, with admin certs, does work, (obviously it would):

`curl -k --cert /etc/elasticsearch/admin.pem --key /etc/elasticsearch/admin.key  -XPOST "https://obscured.host.name:9200/_snapshot/my_repo/my_snapshot/_restore?wait_for_completion=true" -H 'Content-Type: application/json' -d'
{
  "indices": "my_index_to_restore-2019.10.29",
  "ignore_unavailable": true,
  "include_global_state": true
}'
`

I need to allow a few trusted regular users the ability to restore snapshots.  What am I missing?  What did you leave out of the documentation?

t/y 

rlk5546

**Comment by alolita** [comment]
@rlk5546 thanks for flagging. We'll take a look cc: @aetter

**Comment by rlk5546** [comment]
A possible answer here:  https://github.com/opendistro-for-elasticsearch/security/issues/15

Users cannot restore if `"include_global_state": true`.

**Comment by aetter** [comment]
Hi @rlk5546, sure, I've at least changed a couple code samples so that someone who's copy and pasting them doesn't get bitten. https://github.com/opendistro/for-elasticsearch-docs/commit/dba02b2fae0703221ee7eee8601704a37ced9c7e
