### ISSUE TITLE
Helm is duplicated in two repos under opendistro-for-elasticsearch

### ISSUE THREAD

**Issue by DandyDeveloper** [opendistro-for-elasticsearch/community#157]
The same helm chart is currently published in two places, I don't know which one I should be submitting my PRs to: 

https://github.com/opendistro-for-elasticsearch/community
https://github.com/opendistro-for-elasticsearch/opendistro-build

?????

**Comment by DandyDeveloper** [comment]
I have an open PR here: https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/49

But it should probably be here? I don't know. Someone needs to clean up where this helm chart should exist.

**Comment by DandyDeveloper** [comment]
@alolita @hardik-k-shah Really need some eyes from someone on this.

**Comment by alolita** [comment]
Hi @DandyDeveloper The Helm chart to use is in https://github.com/opendistro-for-elasticsearch/opendistro-build and your PR is filed on the correct repo. The original contribution was made in the community repo hence you are seeing two similar versions. The official version is maintained at https://github.com/opendistro-for-elasticsearch/opendistro-build

**Comment by DandyDeveloper** [comment]
@alolita Thank you for the fast response. Is there a good way to communicate with the owners in future about things like this? Or should we just @ sign specific individuals?
