### ISSUE TITLE
ant332-lab-material folder

### ISSUE THREAD

**Issue by krasova** [opendistro-for-elasticsearch/community#158]
Hi, I am trying to find the cloudformation stack for the lab http://eseksworkshop.com/en/
I didn't find this lab in your repo, but was using this fork https://github.com/saadrana219/community/tree/saadrana-ant332

Trying to run this stack and still getting the error

2020-02-13 10:03:30 UTC-0500 | eksdeployapiserver | CREATE_FAILED | Template error: Unable to get mapping for RegionMap::us-west-1::AMI
-- | -- | -- | --

Please let me know where I can find working version of the cloudformation stack for this lab.

Thanks!

**Comment by saadrana219** [comment]
Hi @krasova, the CFN stack is only supporting eu-west-1 region right now, we're actively working on adding support for more regions. You may use the same stack but can only deploy it in eu-west-1 region.

**Comment by alolita** [comment]
Hi @krasova did @saadrana219 's suggestion work for you? Let us know. Thanks!
