### ISSUE TITLE
Support v6.8.6

### ISSUE THREAD

**Issue by jcantrill** [opendistro-for-elasticsearch/community#159]
Support v6.8.6 of Elasticsearch

- [ ] security-parent - Is this needed given v.10.0.4 removes other dependencies?
- [x] [security-advanced-modules](https://github.com/opendistro-for-elasticsearch/security-advanced-modules/pull/78)
- [x] [security-ssl ](https://github.com/opendistro-for-elasticsearch/security-ssl/pull/23)
- [x] [security](https://github.com/opendistro-for-elasticsearch/security/pull/190)
- [x] [security-kibana-plugin](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/142)

What is the proper way to do this given the various circular dependencies?

**Comment by jcantrill** [comment]
cc @hardik-k-shah @alolita

**Comment by alolita** [comment]
Hi @jcantrill Thanks for filing a request. We'll follow up on 6.8.6 support for the security plugin. Will keep you updated.

**Comment by hardik-k-shah** [comment]
We will look into our CI/CD process if we can add requested branch for solving dependency build.
We are also looking into merging 6.x versions in to single repo same as we did for 7.x. Merging repo will make build and test through CI/CD simple.

**Comment by sujithvm** [comment]
@jcantrill I will update you as soon as all artifacts are pushed to S3/cloudfront/docker. 
We have merged `security-ssl`, `security-advanced-modules` and `security-parent` projects into security project so no longer there will be circular dependencies. `security-parent` dependency on security-kibana-plugin is going away too.

**Comment by alolita** [comment]
@sujithvm are the artifacts now available?

**Comment by sujithvm** [comment]
Security artifact is available at `https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-security/opendistro_security-0.10.1.1.zip ` 

Working on getting kibana artifact ready.

**Comment by alolita** [comment]
@jcantrill let us know if this works for you :-)

**Comment by alolita** [comment]
ping @jcantrill

**Comment by jcantrill** [comment]
We have not forgotten about this but are in the midst of closing down Feature freeze.  The intention is to look at a version bump, likely starting sometime next week
