### ISSUE TITLE
PDF Generation and reporting

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/community#16]
A much-sought after feature in Kibana with X-Pack is the ability to export dashboards and visualizations as PDF.

From: https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/issues/3

**Comment by ion-storm** [comment]
CSV/xlsx reports would be nice as well, i'd rename this to just reporting to different file formats

**Comment by vnil1994** [comment]
Yes this is one of the key features missing.

**Comment by sanacl** [comment]
This would be pretty awesome

**Comment by chopchop505** [comment]
Agreed!

**Comment by rlopezro** [comment]
Agreed! We really need CSV/xlsx and PDF.

**Comment by termosa** [comment]
@rlopezro yes!
Please! It is must have

**Comment by raulvc** [comment]
so just checking, there's no current workaround for exporting let's say, a discover search in csv or anything else? (as in, manually installing xpack or something)

**Comment by anlx-sw** [comment]
i also searched for a possibility to do reports with kibana like it is possible with es: https://www.elastic.co/what-is/kibana-reporting

is there any plan that this feature will be added to opendistro directly?
i can't find any open source plugin alternatives to do this currently. does anyone have hints on how do to this simple looking task without expensive licenses?

**Comment by omeganon** [comment]
Adding a voice to this. Definitely would like to export the results of filtered searches...

**Comment by dev-dull** [comment]
+1 for reporting. Specifically, CSV exports of searches on the Discover screen.

**Comment by Kunal-Shah-Bose** [comment]
CSV exports of Discover exports are a must before I can migrate our x-pack cluster to opendistro. Any insight on whether or not this will be worked on?

**Comment by gchiesa** [comment]
+1 on my side. The CSV export feature is the missing step to cover the entire set of must-have functionalities in kibana for opendistro.

**Comment by artemNN** [comment]
+1
really need this feature like Reporting Kibana with X-Pack

**Comment by alexz00** [comment]
+1
In particular, PDF generation from dashboards - possibly with support for scheduling reports.

**Comment by qjadoun** [comment]
Any open source reporting tool that can connect to Elasticsearch as a data store or any tool that can take snapshot of kibana dashboard at a scheduled time?

**Comment by artemNN** [comment]
Not only PDF!
Query result to CSV need too.

**Comment by vrphanse** [comment]
We are having a [community meeting on June 30, 2020](https://discuss.opendistrocommunity.dev/t/community-meeting-on-june-30-2020-kibana-reports-preview-rfc-discussion-and-q-a/3172) to talk about the upcoming reporting feature.

**Comment by bbrendon** [comment]
What was the outcome on this during the meeting?

**Comment by vrphanse** [comment]
Please check out the [RFC for Kibana Reporting](https://github.com/opendistro-for-elasticsearch/kibana-reports/blob/master/docs/dev/Kibana-Reporting-Design-Proposal.md). We have incorporated some of the suggestions we received. Please let me know if you have any questions.

**Comment by jcgraybill** [comment]
Good news - introducing Open Source [Kibana Reporting](https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/reporting/), launched in [Open Distro for Elasticsearch 1.12.0](https://opendistro.github.io/for-elasticsearch/blog/releases/2020/12/opendistro-1-12-0-released/)! 🎉🎉

Big thanks to everyone who asked for this, shared ideas and feedback, and contributed code.
