### ISSUE TITLE
Master not discovered 

### ISSUE THREAD

**Issue by bittu664** [opendistro-for-elasticsearch/community#160]
when  I am trying to use this command   ``` curl -XGET --insecure http://localhost:9200/_cat/indices -u admin:admin ```  It gives me this error!

``` {"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503} ```

**Comment by alolita** [comment]
@bittu664 please provide more context on this issue - about your setup and which plugin?

**Comment by jcgraybill** [comment]
Closing for now. @bittu664 if you're still looking for help, feel free to post a question to the [Open Distro forum](https://discuss.opendistrocommunity.dev/).
