### ISSUE TITLE
Cannot change Kibana IP

### ISSUE THREAD

**Issue by greengeek** [opendistro-for-elasticsearch/community#17]
I just installed opendistro via RPM.  The default setting appears to have kibana listening on 127.0.0.1.  Where can I change this IP address so that it is accessible on my network as 0.0.0.0. or any other IP address.  I noticed the /etc/kibana/kibana.yml file does not have the usual port and host entry.  I added them, made sure they were uncommented, restarted the services, and even the server, and they had no affect.  Is this setting saved elsewhere?  

This is on a clean minimal CentOS 7 install with no firewall or other software installed.  Thanks

**Comment by akezakky555** [comment]
You can add this config  in kibana.yaml

server.host: "0.0.0.0"

**Comment by greengeek** [comment]
Thanks, that worked.  It is strange that all the default settings were removed from the kibana.yml file.  It would be far better to keep the default file there and just add to it the stuff that opendistro provides.  Instead of removing everything that people are use to seeing there.

**Comment by elfisher** [comment]
@greengeek thanks for the feedback. I'll circle back with my team to discuss. Meanwhile it looks like your issue was resolved, so I'm going to go ahead and close this issue.

**Comment by bitonp** [comment]
@greengeek plus one from here too. server.host:0.0.0.0 allows Kibana to run.. but now how do I actually connect to it. Connection refused on all relevant IPs
This is from a standard debian (ubuntu) install .. on a network host.
