### ISSUE TITLE
Can i enable Mutual TLS between Opendistro ES and Logstash also between ES and Kibana?

### ISSUE THREAD

**Issue by ashuagrawalml** [opendistro-for-elasticsearch/community#173]
Can i enable Mutual TLS between Opendistro ES and Logstash also between ES and Kibana? I saw saveral example on enabling one way TLS for encryption. However there is not much online sample config i was able to find for mutual TLS authentication. Any suggesting for the config will help.

Thanks

**Comment by jcgraybill** [comment]
Hi, if you're still looking for help with this, go ahead and post a question to the [Open Distro forums](https://discuss.opendistrocommunity.dev/). Thanks!
