### ISSUE TITLE
Mark down 

### ISSUE THREAD

**Issue by skirankumar** [opendistro-for-elasticsearch/community#176]
Hi when i try to import a image from my local system using markdown visualization in kibana i am unable to perform the action 
I was able to add image from a external google image link but not from a local system 

![image](https://user-images.githubusercontent.com/18494007/81708000-9720d680-948e-11ea-9f37-2de61abd0462.png)

**Comment by jcgraybill** [comment]
Closing for now. @skirankumar if you're still looking for help, feel free to post a question to the [Open Distro forum](https://discuss.opendistrocommunity.dev/).
