### ISSUE TITLE
Building, integration for local testing and debugging documentation ?

### ISSUE THREAD

**Issue by ashishgupta023** [opendistro-for-elasticsearch/community#19]
Is there any documentation on how can we integrate the new version of the plugin (after making code changes and building it)  with local running version of elastic search and kibana to debug and test ?

**Comment by elfisher** [comment]
Hi @ashishgupta023 thanks for the feedback. Adding more clarity on building and installing standalone plugins is something we are working on documenting.

**Comment by elfisher** [comment]
Hi @ashishgupta023 we have an [existing request(https://github.com/opendistro-for-elasticsearch/community/issues/11) for this topic. I'm going to close this one as a duplicate. Please give the other a 👍 Thanks!
