### ISSUE TITLE
Access AWS Elasticsearch Service domains from Opendistro

### ISSUE THREAD

**Issue by rahnagar** [opendistro-for-elasticsearch/community#192]
I am new with Opendistro and got familiar with multiple features that opendistro provides. 
But, one point I couldn't figure out how can I access domains existing at Elasticsearch service at AWS cloud from my local opedistro setup?
My use case is to do search queries on some index available at Elasticsearch service domain through local opendistro setup.

**Comment by jcgraybill** [comment]
Hi, if you're still looking for help with this, go ahead and post a question to the [Open Distro forums](https://discuss.opendistrocommunity.dev/). Thanks!
