### ISSUE TITLE
alternative location for elasticsearch.keystore

### ISSUE THREAD

**Issue by wyllys66** [opendistro-for-elasticsearch/community#193]
When running elastic in containerized environment like Kubernetes, is it possible to configure the elasticsearch.keystore to be on a persistent filesystem, somewhere other than in /usr/share/elasticsearch/config ? 

The problem is that any changes added to the keystore after the container starts are currently lost whenever the container is restarted.  For example, when configuring an S3 repository for storing snapshots, the access and secret keys are stored in the keystore, but if the pod is restarted, the additions are lost and the snapshot storage fails until the keystore is updated again.

Because each node has its own copy of the keystore, it is tedious to have to go to each pod and update the keystore with the right values. It would be much easier if the keystore location was configurable and could be put on a shared and persistent filesystem.

**Comment by AswinKakarot** [comment]
I ran into the same issue, so I basically ported the code from elastic/helm-charts repo. Where the idea is to attach an volume mount and run an initContainer to initialize the keystore items. Attach the same volume in /usr/share/elasticsearch/config/elasticsearch.keystore. It worked like a charm for me. I could create a PR if you guys want.

**Comment by Schnitzel** [comment]
@AswinKakarot yes please! <3

**Comment by AswinKakarot** [comment]
@Schnitzel I've created a PR. You can take a look at it
