### ISSUE TITLE
Link for CLA

### ISSUE THREAD

**Issue by junawaneshivani** [opendistro-for-elasticsearch/community#196]
Hi All, 

My team has been working on porting opendistro to power architecture. Wanted to make sure if there is any CLA required for code contributions?

I could see it listed [here](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/CONTRIBUTING.md#licensing) but couldn't find any document links.

**Comment by junawaneshivani** [comment]
Any comments on this ?

**Comment by jcgraybill** [comment]
Thanks for asking. Per https://opendistro.github.io/for-elasticsearch/contribute.html contributing to Open Distro for Elasticsearch doesn't require a CLA, so I've updated CONTRIBUTING.md in the build repo to reflect this. I hope your project to port to power is going well.
