### ISSUE TITLE
Please Provide Steps to Ingest CloudWatch Data to Opendistro elasticsearch EC2 based

### ISSUE THREAD

**Issue by ashokchenga123** [opendistro-for-elasticsearch/community#20]
Please Provide Steps to Ingest CloudWatch Data to Opendistro  elasticsearch  which is running of EC2.

**Comment by Jon-AtAWS** [comment]
Thanks for letting us know about your interest! We'll be blogging about Open Distro for Elasticsearch quite a bit, and I've added your topic.

For others reading this, please let us know what you're interested in reading about!

Jon

**Comment by alolita** [comment]
@ashokchenga123 - can you provide more details about your use case for ingesting CW data using Open Distro?

**Comment by ashokchenga123** [comment]
EC2 is running an open-distro version of elastic search. below are uses cases for data ingestion

1. AWS Cloudwatchlogs collects application logs from ec2-servers ( example apache-tomcat, MySQL ) and aws services like api-gw, lambda. now from cloudwatch logs, we need to stream it to elastic search open-distro.

2. Streaming the IOT data via IOT rules to elastic search running open-distro.

3. CloudWatch Metrics data needs to be sent to elastic search open-distro.

Note: Today there is no stable solution which can guarantee a stable transmission of data from AWS cloudwatch/logs and from other aws services to open-distro elastic search. If you build one stable data ingestion plugin this will of good. This will help in creating an alert and monitoring system out of the open-distro elastic search.

Thanks

**Comment by ashokchenga123** [comment]
@alolita  - updated with details above

**Comment by eirc** [comment]
Hello, has there been any progress here or any change whatsoever? It seems there are a few alternatives but all with their shortcomings:

- Stream logs directly with AWS (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_ES_Stream.html) should be the simplest to setup but the cost can get out of hand. If I understand correctly we're talking about a lambda call for every single log line (or maybe a batch of them I'm not sure) so it would scale out of hand very quickly.

- Filebeat CloudWatch input (https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-awscloudwatch.html) is part of X-Pack so you'd need to get a full subscription going and these are not cheap either.

- Cloudwatchlogsbeat (https://github.com/e-travel/cloudwatchlogsbeat) is a beat exactly for this purpose so while it fits the bill exactly it's not official so updates may not be always on time (disclaimer: I've been slightly involved in this beat's making).

So are there any more suggestions that I'm missing maybe? Is any of these the best recommendation given the current context?

**Comment by jcgraybill** [comment]
Hi, I'm going to close this issue and suggest opening a question on the [Open Distro forums](https://discuss.opendistrocommunity.dev/c/feedback/6), where you might have more luck getting a conversation going.

**Comment by FirstWhack** [comment]
> Thanks for letting us know about your interest! We'll be blogging about Open Distro for Elasticsearch quite a bit, and I've added your topic.
> 
> For others reading this, please let us know what you're interested in reading about!
> 
> Jon

Could I get a link to this blog post?

**Comment by Jon-AtAWS** [comment]
Hi @jhawins,

I don't think we ever specifically wrote a post on sending CloudWatch data to ODFE. The ODFE posts are all here: https://opendistro.github.io/for-elasticsearch/blog/. ODFE has been rolled into OpenSearch (https://github.com/opensearch-project). We're blogging on OpenSearch here: https://opensearch.org/blog/.

https://cloudtrail.aesworkshops.com/ is a lab that we use with Amazon Elasticsearch Service. It's ancient, and may not work out of the box, but it has the core concepts and comes with a CloudFormation template. You could modify the CloudWatch-generated lambda to send the data to an ODDE/OpenSearch endpoint on EC2.

J-
