### ISSUE TITLE
Admin cannot use _restore endpoint

### ISSUE THREAD

**Issue by bollohz** [opendistro-for-elasticsearch/community#202]
We have correctly configurated ES OpenDistro with Amazon S3 plugin in order to take snapshot. Everything works well with `PUT _snapshot/my-bucket/date` endpoint. 
Calling `POST _snapshot/my-bucket/date/_restore` endpoint with Admin credentials ( user admin created by default, typically -u admin:admin) OpenDistro returns a 401.

**Comment by jcgraybill** [comment]
Hi, if you're still looking for help with this, go ahead and post a question to the [Open Distro forums](https://discuss.opendistrocommunity.dev/). Thanks!
