### ISSUE TITLE
Add support for Gantt Chart visualization plugin

### ISSUE THREAD

**Issue by anirudha** [opendistro-for-elasticsearch/community#210]
Enable Kibana visualizations to use Gantt charts and integrate with Plotly / Vis.js

**Comment by cascandaliato** [comment]
@anirudha, do you have examples of the Gantt charts this plugin is going to render?

I am working on a timeline chart at work using [Vega](https://vega.github.io/vega) and I'm planning to make a Kibana plugin out for it, but I would prefer using this Gantt chart instead if it meets my requirements.

**Comment by jcgraybill** [comment]
> 
> 
> @anirudha, do you have examples of the Gantt charts this plugin is going to render?
> 
> I am working on a timeline chart at work using [Vega](https://vega.github.io/vega) and I'm planning to make a Kibana plugin out for it, but I would prefer using this Gantt chart instead if it meets my requirements.

I created a new issue to track this question: https://github.com/opendistro-for-elasticsearch/kibana-visualizations/issues/10  - and closing this one, since the feature is launched!
