### ISSUE TITLE
Non-technical: lawsuit outcome

### ISSUE THREAD

**Issue by neographikal** [opendistro-for-elasticsearch/community#211]
Don't know where to ask this but I found a lot of article from 2019 that announced Elastic is suing Amazon for copyright infringement. I can't find any updates about the progress of the lawsuit. My suggestion would  be to write something non-technical: a blog post detailing the status of the lawsuit and chances of Open Distro. I'm hesitant to start with Open Distro because of this and that is exactly Elastic's aim it would seem.

**Comment by neographikal** [comment]
Any updates?

**Comment by CarlMeadows** [comment]
To be clear - Elastic does not have a copyright infringement case against Amazon - they have filed a lawsuit against floragunn GmbH - a security software vendor that makes Search Guard and provided source code which is used in the Open Distro for Elasticsearch security plug-in. We have responded to these claims publicly here: https://aws.amazon.com/blogs/opensource/launching-open-distro-for-elasticsearch-security-features-on-amazon-elasticsearch-service/

A key quote from that post: "We want to make the community aware that AWS performed our own due diligence prior to partnering with floragunn and found no evidence that Search Guard misappropriated any copyrighted material. Additionally, we evaluated all of the code specified by Elastic in their litigation, as well as engaged third party experts, and we are confident that there is no basis to Elastic’s claims.

We find it unfortunate that Elastic has resorted to litigation against floragunn, a valuable member of the Elasticsearch community. This kind of behavior is misaligned with the spirit of open source and is detrimental to the vibrancy of the community."

Hopefully this helps put your concerns at ease but please reach out to us if you would like to discuss it further.

**Comment by neographikal** [comment]
Thanks Carl, that post is over a year old already. An update would be nice, I can imagine more information is now available about how much at risk the Open Distro project now is by using the code from Search Guard. I know a few people that are curious :)
