### ISSUE TITLE
Use SAML with kibana and another http authentication mechanism

### ISSUE THREAD

**Issue by juliennix** [opendistro-for-elasticsearch/community#219]
Hello,

We have setup the SAML authentication (was not simple).
We tried to use SAML authentication and http basic authentication (via ldap or internal users) but as the SAML redirects directly to our Azure Active Directory.
Is it possible to have both ? If yes, great, how could it be setup ? If not, I will create a feature request ticket.

Many thanks for your work and this great tool.
Kind regards,
Julien Nix

**Comment by bbarani** [comment]
@zengyan-amazon , can you provide your comments here?

**Comment by zengyan-amazon** [comment]
@juliennix Currently security Kibana plugin only support 1 authentication type, while Elasticsearch security plugin supports chaining the auth handlers. If you want Kibana to authenticate users using both SAML and basic auth, it is not supported.

if you want Kibana users to login using SAML, and your systems can make calls to Elasticsearch using basic auth, that is supported. To do this, in your Elasticsearch security plugin config, you can set basic auth order to `0` and `challenge` to `false`, then config SAML auth order to `1`, and `challenge` to `true`.
