### ISSUE TITLE
Tenant indices migration failed

### ISSUE THREAD

**Issue by greengeek** [opendistro-for-elasticsearch/community#22]
After rebooting my RPM install, I am now getting a Kibana Status is Yellow.  It is showing Plugin Status as 

> plugin:opendistro_security@6.5.4 | Tenant indices migration failed

and will not let me switch to other pages within Kibana.  How might I fix this error?  Thanks

**Comment by hardik-k-shah** [comment]
This was addressed and merged through this PR: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/2

**Comment by greengeek** [comment]
i just did a new install following https://opendistro.github.io/for-elasticsearch-docs/docs/install/rpm/ and it is still doing the same thing.  How would I manually apply the above PR to an existing server install?

**Comment by hardik-k-shah** [comment]
Hey greengeek@ 
PR was merged but it is pending for release. We will be releasing it soon.

**Comment by greengeek** [comment]
What would be the fix for systems that already have open distro installed?

**Comment by elfisher** [comment]
@greengeek in the meantime, if you are using docker-compose you can overwrite the js file causing the issue with the patch. **Credit to MqewuD52 on [our forums](https://discuss.opendistrocommunity.dev/t/about-tenant-indices-migration-failed-error-in-kibana/138/3?u=elifish)**. Below are the steps:

1. Copy this [fixed file](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/2/files#diff-b52b417cc96d68edc4ef58df2f56c06c) to your local working path.
2. Update your docker-compose.yml file to mount this file over the existing file. You can do this by adding this line in the Kibana section: 
```
volumes: 
  - ./migrate_tenants.js:/usr/share/kibana/plugins/opendistro_security/lib/multitenancy/migrate_tenants.js
```
3. restart with `docker-compose down` then `docker-compose up`

If you are using RPM just swap the fixed js file over the old one and restart kibana.
