### ISSUE TITLE
[SAML] Cannot have IdP initiated login and SP initiated login at the same time with Okta

### ISSUE THREAD

**Issue by orsifacundo** [opendistro-for-elasticsearch/community#223]
Hi! I've followed the SSO blogpost to configure SAML with Okta and it works fine but the problem is that:

- When configuring the ACS URL on Okta (Single Sign On URL parameter) as `/_opendistro/_security/saml/acs/` then it will only let me authenticate as SP initiated login.
- When configuring the ACS URL on Okta (Single Sign On URL parameter) as `/_opendistro/_security/saml/acs/idpinitiated` then it will only let me authenticate as IdP initiated login.

Is this suppose to work like this? Is there any workaround to have both authentication flows at the same time? I tried creating 2 apps on Okta and 2 configs on Open Distro with different order but it doesn't work.

Regards.

**Comment by jcgraybill** [comment]
Hi, if you're still looking for help with this, go ahead and post a question to the [Open Distro forums](https://discuss.opendistrocommunity.dev/). Thanks!
