### ISSUE TITLE
Duplicate Helm Charts for ODFE!

### ISSUE THREAD

**Issue by GezimSejdiu** [opendistro-for-elasticsearch/community#227]
Hi ODFErs, 

just came across that there are two different places (**[opendistro-build/helm](https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm)**, [community/open-distro-elasticsearch-kubernetes/helm](https://github.com/opendistro-for-elasticsearch/community/tree/master/open-distro-elasticsearch-kubernetes/helm)) where the helm charts for the ODFE are kept and was wondering if this is by mistake? or there is a different reason for keeping them there. I know that the ODFE documentation explicitly [points out the right one](https://opendistro.github.io/for-elasticsearch-docs/docs/install/helm/#install-using-helm) but just wanted to be sure about that.

Best regards,
Gezim

**Comment by jcgraybill** [comment]
Hi Gezim, thanks for asking. We're in the process of migrating the helm chart from the community repo into the build repo - so yes, please use the build-repo helm chart referred to the documentation. Once we clean up a few outstanding PRs in the community repo we'll remove it.

Jules
