### ISSUE TITLE
How are people handling ES configuration of /_settings ? 

### ISSUE THREAD

**Issue by js-timbirkett** [opendistro-for-elasticsearch/community#230]
Hi 👋 

I may have missed something somewhere... Since Elasticsearch v7 you can no longer set index related configurations in Elasticsearch config files. In particular:
```yaml
index.refresh_interval: 30s
index.merge.scheduler.max_thread_count: 1
```

You must now PUT them to the API. The only problem is that, even as the admin user you get an error:
```sh
curl -k -XPUT 'https://admin:<NotAPassword>@localhost:9200/_settings' -d '{
  "index.refresh_interval": "30s",
  "index.merge.scheduler.max_thread_count": 1
}' -H 'Content-Type: application/json'
```
response:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
      }
    ],
    "type": "security_exception",
    "reason": "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
  },
  "status": 403
}
```

Which I guess is because the admin user is missing the permission mentioned in the logs:
```json
{
  "type": "server",
  "timestamp": "2020-11-30T11:06:12,885Z",
  "level": "WARN",
  "component": "c.a.o.s.p.OpenDistroSecurityIndexAccessEvaluator",
  "cluster.name": "elasticsearch",
  "node.name": "opendistro-es-master-0",
  "message": "indices:admin/settings/update for '_all' indices is not allowed for a regular user",
  "cluster.uuid": "mr9s8WuXR6CIaF9SofbpRw",
  "node.id": "zNJ2cqSdThOHeZTfvhC3ZA"
}
```

With regards to setting these options, am I missing some way to create these settings with `securityadmin.sh` or some other mechanism in the Helm charts? How are others handling configuration of these sorts of `_settings`?

Thanks in advance :)

**Comment by jcgraybill** [comment]
Hi, if you're still looking for help with this, go ahead and post a question to the [Open Distro forums](https://discuss.opendistrocommunity.dev/). Thanks!
