### ISSUE TITLE
OpenDistro - Kibana - Error: failed parsing SAML config

### ISSUE THREAD

**Issue by rakesh-007** [opendistro-for-elasticsearch/community#232]
Hi Team,
I want to integrate Okta with OpenDistro Using Helm,
Please find my kibana.yml & config.yml (ElasticSearch).

**_### Kibana.yml_** :-

elasticsearch.hosts: https://opendistro-es-client-service:9200
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist:
- securitytenant
- Authorization
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
opendistro_security.auth.type: saml
opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred:
- Private
- Global
opendistro_security.readonly_mode.roles:
- kibana_read_only
server.host: "0"
server.name: kibana
server.xsrf.whitelist:
- /_opendistro/_security/saml/acs
- /_opendistro/_security/saml/logout

### **_config.yml (ElasticSearch)_** 

_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
    # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
    # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
    #filtered_alias_mode: warn
    #do_not_fail_on_forbidden: false
    #kibana:
    # Kibana multitenancy
    #multitenancy_enabled: true
    #server_username: kibanaserver
    #index: '.kibana'
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        #internalProxies: '.*' # trust all internal proxies, regex pattern
        #remoteIpHeader:  'x-forwarded-for'
        ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
        ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
        ###### and here https://tools.ietf.org/html/rfc7239
        ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
        type: basic
        challenge: false
        authentication_backend:
        type: internal
      saml_auth:
        order: 1
        description: "SAML provider"
        http_enabled: true
        transport_enabled: false
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_file: /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/metadata.xml  #SAML's metadata url
              entity_id: http://www.okta.com/exk21h4f443I7uHIJ5d6 #SAML's IdP entity ID, provided by your IdP
            sp:
              entity_id: kibana-saml
              forceAuthn: true
            kibana_url: *****************
            subject_key: UserID
            roles_key: Role
            exchange_key: Rd0SnYhRqNQIWhxSWzPkrvdxigyH3fHw
        authentication_backend:
          type: noop    
    authz:
      roles_from_myldap:
        description: "Authorize via LDAP or Active Directory"
        http_enabled: false
        transport_enabled: false
        authorization_backend:
          # LDAP authorization backend (gather roles from a LDAP or Active Directory, you have to configure the above LDAP authentication backend settings too)
          type: ldap
          config:
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: true
            hosts:
            - localhost:8389
            bind_dn: null
            password: null
            rolebase: 'ou=groups,dc=example,dc=com'
            # Filter to search for roles (currently in the whole subtree beneath rolebase)
            # {0} is substituted with the DN of the user
            # {1} is substituted with the username
            # {2} is substituted with an attribute value from user's directory entry, of the authenticated user. Use userroleattribute to specify the name of the attribute
            rolesearch: '(member={0})'
            # Specify the name of the attribute which value should be substituted with {2} above
            userroleattribute: null
            # Roles as an attribute of the user entry
            userrolename: disabled
            #userrolename: memberOf
            # The attribute in a role entry containing the name of that role, Default is "name".
            # Can also be "dn" to use the full DN as rolename.
            rolename: cn
            # Resolve nested roles transitive (roles which are members of other roles and so on ...)
            resolve_nested_roles: true
            userbase: 'ou=people,dc=example,dc=com'
            # Filter to search for users (currently in the whole subtree beneath userbase)
            # {0} is substituted with the username
            usersearch: '(uid={0})'
            # Skip users matching a user name, a wildcard or a regex pattern
            #skip_users:
            #  - 'cn=Michael Jackson,ou*people,o=TEST'
            #  - '/\S*/'
      roles_from_another_ldap:
        description: "Authorize via another Active Directory"
        http_enabled: false
        transport_enabled: false
        authorization_backend:
          type: ldap

Getting this Error in Kibana Logs :-1: 

user-agent":"curl/7.29.0","host":"localhost:5601","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":500,"responseTime":8,"contentLength":9}
,"message":"HEAD /auth/saml/login?nextUrl=%2F 500 8ms - 9.0B"}
Error: failed parsing SAML config
    at SecurityClient.getSamlHeader (/usr/share/kibana/plugins/opendistro_security/server/backend/opendistro_security_client.js:163:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
{"type":"log","@timestamp":"2020-12-10T11:28:34Z","tags":["error","plugins","opendistroSecurity"],"pid":1,"message":"Failed to get saml header: Error: Error: failed parsing SAML 
config"}
{"type":"error","@timestamp":"2020-12-10T11:28:34Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Er
ror\n    at HapiResponseAdapter.toError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:132:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/kibana/s
rc/core/server/http/router/response_adapter.js:86:19)\n    at HapiResponseAdapter.handle (/usr/share/kibana/src/core/server/http/router/response_adapter.js:81:17)\n    at Router.
handle (/usr/share/kibana/src/core/server/http/router/router.js:162:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null
,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"?nextUrl=%2F","query":{"nextUrl":"/"},"pathname":"/auth/saml/login","path":"/auth/saml/login?nextUrl=%2
F","href":"/auth/saml/login?nextUrl=%2F"},"message":"Internal Server Error"}
{"type":"response","@timestamp":"2020-12-10T11:28:34Z","tags":[],"pid":1,"method":"head","statusCode":500,"req":{"url":"/auth/saml/login?nextUrl=%2F","method":"head","headers":{"
user-agent":"curl/7.29.0","host":"localhost:5601","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":500,"responseTime":13,"contentLength":9
},"message":"HEAD /auth/saml/login?nextUrl=%2F 500 13ms - 9.0B"}
{"type":"response","@timestamp":"2020-12-10T11:28:35Z","tags":[],"pid":1,"method":"get","statusCode":401,"req":{"url":"/app/login?nextUrl=%2F","method":"get","headers":{"host":"1
0.0.2.35:5601","user-agent":"kube-probe/1.16+","accept-encoding":"gzip","connection":"close"},"remoteAddress":"10.0.2.1","userAgent":"10.0.2.1"},"res":{"statusCode":401,"response
Time":32,"contentLength":9},"message":"GET /app/login?nextUrl=%2F 401 32ms - 9.0B"}

**Comment by rakesh-007** [comment]
@hermanhmlee

**Comment by chrandal** [comment]
@rakesh-007 Did you find a solution to this?  I am seeing the same error. Thanks.

**Comment by DiegoFernandodaSilva** [comment]
@chrandal  i'm facing the same trouble, any solution? Thanks.

**Comment by gferrette** [comment]
Hello!

Please, i'm facing the same issue, do you guys have a solution?

Thanks in advance!
