### ISSUE TITLE
Error in visualization [esaggs] >"no message"

### ISSUE THREAD

**Issue by k343497** [opendistro-for-elasticsearch/community#234]
Dear Opendistro team,

We are currently getting the KIbana visualization error message when we are loading a large number of data.
However, the error message does not give any issue type or message after the [easggs] >, and we are unable to find out what exactly the error is.
The error message is showing as below:
![Screenshot 2020-12-16 171948](https://user-images.githubusercontent.com/22550212/102332233-c9675900-3fc6-11eb-8672-9107ee5c07f6.jpg)

Please give some suggestions about the error.

Thank you.

**Comment by bbarani** [comment]
@seanneumann, can you provide any suggestion here?

**Comment by jcgraybill** [comment]
Hi, if you're still looking for help with this, go ahead and post a question to the [Open Distro forums](https://discuss.opendistrocommunity.dev/). Thanks!
