### ISSUE TITLE
Forking plan given upstream license changes?

### ISSUE THREAD

**Issue by mhart** [opendistro-for-elasticsearch/community#238]
The [current FAQ](https://opendistro.github.io/for-elasticsearch/faq.html) says:

> Are you forking Elasticsearch?
> No. Open Distro for Elasticsearch is not a fork. In fact, we intend to continue making contributions to the Apache 2.0-licensed Elasticsearch code.

In light of [Elastic's recent license change](https://www.elastic.co/blog/licensing-change), core ES code will no longer be Apache 2.0 licensed from 7.11 onwards.

My guess is the text of the FAQ needs to be updated now – it would be good to hear what Open Distro's plan is going forward w/ regards to a fork (I assume one will be needed now?) and what goals it has for feature parity w/ Elastic's project as new versions are rolled out.

**Comment by ecki** [comment]
Also interested in this topic. Especially if you plan to produce Maven Central artifacts for client libraries, and if so, under which groupID this will happen. We would prefer to have a dedicated group (even when this is much more work) so in order to whitelist only the groupid which is known to stay FOSS.

**Comment by jcgraybill** [comment]
Thanks for asking, and great point about Maven Central. We're working on this very plan now - more to come shortly.

**Comment by jcgraybill** [comment]
Hi - following up on this question. You can read about the plan on the AWS Open Source blog here: https://aws.amazon.com/blogs/opensource/stepping-up-for-a-truly-open-source-elasticsearch/

**Comment by mhart** [comment]
Great, thanks for that @jcgraybill – I think once the Open Distro FAQ is updated to reflect that plan we can close this out.

**Comment by jcgraybill** [comment]
We're working on that very thing. In the meantime, feel free to ask any follow-up questions in this thread in the forums: https://discuss.opendistrocommunity.dev/t/recent-elastic-co-licensing-change-announcment/4583/46

**Comment by killswitch-GUI** [comment]
Amazing news!

**Comment by jcgraybill** [comment]
FYI we've added several questions about the fork plan to the [Open Distro FAQ](https://opendistro.github.io/for-elasticsearch/faq.html). There will also be updates on the [Open Distro blog](https://opendistro.github.io/for-elasticsearch/blog/), and discussion in the [forums](https://discuss.opendistrocommunity.dev/c/forking-elasticsearch-kibana/50). 

Thanks for all the interest! I'm going to close this issue, and we can keep the conversation going in the forums and blog.
