### ISSUE TITLE
Timelion poor syntax error message

### ISSUE THREAD

**Issue by okvittem** [opendistro-for-elasticsearch/community#241]
Would you say from the Timelion program 
> .es('*') 

is is easy to understand what the error is when the error message is :
> Timelion request error: undefined SyntaxError: {"type":"incompleteFunction","function":"es","location":{"min":0,"max":3},"text":".es"}

This is Kibana 1.12.0 and the its in a Dasboard with integrated Timelion.

The syntax error is that single quotes is used instead of double ones. This is a change from the previous not so integrated version of timelion which still support using single quotes by the way. Took me some time to figure out and fix my scripts after the upgrade.

**Comment by jcgraybill** [comment]
Hi, if you're still looking for help with this, go ahead and post a question to the [Open Distro forums](https://discuss.opendistrocommunity.dev/). Thanks!
