### ISSUE TITLE
Support of python client library

### ISSUE THREAD

**Issue by Pranali04796** [opendistro-for-elasticsearch/community#242]
Can we use python elasticsearch client library or elasticsearch-dsl library with open distro.?
Thanks in advance..I have tested but showing some protocol error.
What would be a solution for using python scripts for interacting with ODFE?

**Comment by jcgraybill** [comment]
You sure can. Open Distro, by default, starts up with SSL enabled, self-signed certs, and a default 'admin' user. You'll want to customize the latter two before running in production, of course. 

To connect the python client to this out-of-the-box configuration on localhost, you would do something like this:

```
from elasticsearch import Elasticsearch
es = Elasticsearch(['https://admin:admin@localhost:9200/'],
			use_ssl=False,
                        verify_certs=False,
                        ssl_show_warn=False)

res = es.index(index="sample", id=1, body={ 'hello': 'world'} )
print(res['result'])

res = es.get(index="sample", id=1)
print(res['_source'])
```

The [Transport docs](https://elasticsearch-py.readthedocs.io/en/v7.10.1/transports.html) give more details about connection options.

**Comment by Pranali04796** [comment]
Thank you. @jcgraybill

**Comment by alexzubiaga** [comment]
Looks like version 7.14 of the client is checking the Elastic Search version and failing with an UnsupportedProductError.
see [ProductChecker](https://github.com/elastic/elasticsearch-py/blob/584467de50749d1ce1c979976d3cfddf70ad75f0/elasticsearch/transport.py#L606)

**Comment by ThepoisonedApple** [comment]
i was having this error.Opendistro 1.13.2 uses 7.10.2 elastic in back so just using elasticsearch-py 7.10.1 is solved error for my case.
