### ISSUE TITLE
APM UI Missing

### ISSUE THREAD

**Issue by kristianpaul** [opendistro-for-elasticsearch/community#25]
As i understand APM agents should connect to elastic open distro but there is no UI in Kibana as today to visualize application traces and performance as in elasticsearch  

[1] https://discuss.opendistrocommunity.dev/t/apm-agent-support/200

**Comment by sabareeshkkanan** [comment]
This is one last feature that is stopping us from moving to open distro. If we can get some guidance on when we can expect this feature will help lot of us plan. Again thanks for this open distro initiative !!!

**Comment by francisminu** [comment]
Same here. OpenDistro is amazong, but one thing that we greatly miss is the APM UI so that we can see all the distributed tracing information and the performance metrics all at one place

**Comment by sabareeshkkanan** [comment]
Another ideal solution could be building dashboards for open metrics, micrometer.

**Comment by sideshowjay** [comment]
Just commenting that the lack of the APM UI would also prevent us from moving to OpenDistro.

**Comment by vegardx** [comment]
You could always use something like Jaeger with ElasticSearch as storage backend. Seems like you should also be able to use the APM Agent and Server, and display it in Jaeger UI. 

Alternative 1: https://openapm.io/landscape?collector=elastic-apm&agent=elastic-apm-agent&storage=elasticsearch&visualization=jaeger-query
Alternative 2: https://openapm.io/landscape?instrumentation-lib=jaeger-client&collector=jaeger-agent,jaeger-collector&storage=elasticsearch&visualization=jaeger-query

**Comment by bgagnon** [comment]
APM UI is part of X-Pack. It cannot be combined with OpenDistro, as far as I understand the Elastic License.

**Comment by takugawa** [comment]
some time ago the module was paid, thanks for their wonderful product, now the security is free without ldap, maybe it will be the same with the APM, we also lack this module, by the way I created a channel in a telegram where you can quickly ask each other questions https://t .me/opendistro

**Comment by lucasfernandesmontdata** [comment]
+1 for this feature. APM UI would be awesome, to stop using grafana either :)

**Comment by bgagnon** [comment]
> some time ago the module was paid, thanks for their wonderful product, now the security is free without ldap, maybe it will be the same with the APM

APM is _free_, but it's under the Elastic license, not the Apache license. It's included in the Basic subscription:
https://www.elastic.co/subscriptions

Open Distro works with the Apache (OSS) version of Elasticsearch, not the Elastic license version (also known as "X-Pack").
So you can use APM today, just not with OpenDistro.

**Comment by jcgraybill** [comment]
Heya - note the recent alpha launch of Trace Analytics in Open Distro for Elasticsearch: https://opendistro.github.io/for-elasticsearch/blog/releases/2020/12/announcing-trace-analytics/
