### ISSUE TITLE
Docker Images Release for OpenDistro v0.7.0.1

### ISSUE THREAD

**Issue by gabrielcalderon** [opendistro-for-elasticsearch/community#27]
A new tag was released for OpenDistro v0.7.0.1 but there has not been any Docker Images releases so far. When is this scheduled to happen?

Thanks!

**Comment by alolita** [comment]
@gabrielcalderon should be available in the next few days.

**Comment by weand** [comment]
Are you going to release the Docker image **sources** as well. As of today they are not open sourced.

:+1: for publishing them.

**Comment by CarlMeadows** [comment]
Hi - sorry I didn't close this early - the new images are available. 

https://discuss.opendistrocommunity.dev/t/open-distro-for-elasticsearch-0-7-1-is-now-available/329

**Comment by gabrielcalderon** [comment]
Thanks! 👍

**Comment by siddharthlatest** [comment]
@CarlMeadows Sorry to jump on a closed thread, but I don't see the docker image source in the above link you mentioned.

**Comment by CarlMeadows** [comment]
Hiya - No worries. If you check Docker Hub:

https://hub.docker.com/r/amazon/opendistro-for-elasticsearch/tags
https://hub.docker.com/r/amazon/opendistro-for-elasticsearch-kibana/tags

You will see the 0.7.1 images which have the fix. We also will likely be publishing a 0.8.0 release today that will be updated for ES 6.6.

Thanks.
