### ISSUE TITLE
Default monitoring

### ISSUE THREAD

**Issue by megalithSE** [opendistro-for-elasticsearch/community#29]
I would like to know why alerting and security plugins is in but not graph and monitoring parts. They are default in ES, the none oss flavor?
It would be nice if we could get a opendistro_monitor plugin going. I know PerfTop is in OD but for none CLI users the default monitoring is good enough. And I can't really switch right now if that is not in place. 

Version I'm running: 
elasticsearch-oss.noarch 6.5.4-1
Plugins running 0.7.0.0

**Comment by lukas-vlcek** [comment]
I think this is broader topic. Different users prefer different monitoring tools depending on the context/environment they run ES cluster in. For example if users run ES cluster on top of Kubernetes and they want oss monitoring solution they might prefer Prometheus (and Loki in the future).

Also, monitoring without set of alerting rules is not much useful. IMO you always have to think about monitoring AND alerting going hand in hand. And you also should provide some dashboard for collected metrics (like Grafana for example).

So providing some default monitoring/alerting/dashboarding package as part of open distro means that you have to make some opinionated decision and not everyone will like it or use it. 
 
My 2 cents.

**Comment by mporracindie** [comment]
I believe you can easily defer between elastic cluster monitoring and infrastructure monitoring. Ideally you would like both on the same place with alarms but for example the paid version of elastics (the platinum one) offer a "Monitoring" feature inside the same cluster that is really useful and gives metrics regarding the status of the cluster/indices and so on.

It could be a optional but useful feature to have.

**Comment by lukas-vlcek** [comment]
I think open distro should focus on integration with wide variety of (existing and future) monitoring tools instead of building new extra tool.
