### ISSUE TITLE
Some errors in the security-admin documentation

### ISSUE THREAD

**Issue by bigfishman** [opendistro-for-elasticsearch/community#30]
Some errors in the documentation：

https://opendistro.github.io/for-elasticsearch-docs/docs/security/security-admin/

in the chapter  Apply configuration changes
the   description
`./securityadmin.sh -cd ../sgconfig -ts ... -tspass ... -ks ... -kspass ...`

Not sgconfig but securityconfig

**Comment by aetter** [comment]
Hi @bigfishman, thanks a ton. Should be fixed now. https://github.com/opendistro/for-elasticsearch-docs/commit/ccd849466dba9cc1580dbe81679da9624a9bea31
