### ISSUE TITLE
Create hash for new passwort: Permisson denied

### ISSUE THREAD

**Issue by fwiedmann** [opendistro-for-elasticsearch/community#38]
I trying to create a new password hash for the admin user like in the instructions: 
https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker-security/#change-passwords-for-read-only-users

but when I execute the command I get a "Permission denied". After setting executable rights with "chmod +x /usr/share/elasticsearch/plugins/opendistro_security/tools/hash.sh " it works perfectly.

**Comment by elfisher** [comment]
Hi @fwiedmann are you running this script in docker?

**Comment by fwiedmann** [comment]
hey @elfisher yes I'm running the script in docker. I tried both version 0.7.0 and 0.7.1

**Comment by aetter** [comment]
I can only reproduce this problem if I modify the command from the docs:

```bash
(From the docs)
$ docker exec 2524939b0780 /bin/sh /usr/share/elasticsearch/plugins/opendistro_security/tools/hash.sh -p newpassword
$2y$12$JcRX7194xUyiL1aRYQVW3ekIWyewV6vu5/8Jx2bUx6F0A24RH.UmK

(Variation that excludes /bin/sh)
$ docker exec 2524939b0780 /usr/share/elasticsearch/plugins/opendistro_security/tools/hash.sh -p newpassword
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"/usr/share/elasticsearch/plugins/opendistro_security/tools/hash.sh\": permission denied": unknown

$ docker exec 2524939b0780 chmod +x /usr/share/elasticsearch/plugins/opendistro_security/tools/hash.sh

$ docker exec 2524939b0780 /usr/share/elasticsearch/plugins/opendistro_security/tools/hash.sh -p newpassword
$2y$12$6n53ufwiBjVFZhmfW6HiL.on6dniEhqGEpgTcnVTK/4kB5mcozyIG
```

I've put a tip into the documentation, but I think the copy and pasted command as-is should still do the trick

**Comment by ryandawsonuk** [comment]
FWIW I found I had to exec into the container and change permissions first. [Others have found this too.](https://www.gitmemory.com/issue/opendistro-for-elasticsearch/community/38/479352643)
