### ISSUE TITLE
LICENSE link in README.md is 404

### ISSUE THREAD

**Issue by MarkAtwood** [opendistro-for-elasticsearch/community#44]
LICENSE link in README.md is 404
Either place a LICENSE file in this directory, or point at the LICENSE file in the root of the repo

**Comment by halkazzar** [comment]
interesting, the link works fine for me. Link points to [https://github.com/opendistro-for-elasticsearch/community/blob/master/LICENSE](https://github.com/opendistro-for-elasticsearch/community/blob/master/LICENSE) which opens OK.

**Comment by alolita** [comment]
Works for me too @MarkAtwood
