### ISSUE TITLE
No RPM available for separated Kibana plugins

### ISSUE THREAD

**Issue by fabdslv** [opendistro-for-elasticsearch/community#46]
The RPM that OpenDistro provides includes Kibana + OpenDistro plugins for Kibana and these installations cannot be decorrelated. This means that we cannot provide our own Kibana distribution, but also that we cannot install plugins separately.

This is something we can do with OpenDistro ES plugins because the global RPM references  ElasticSearch RPM + OpenDistro plugins separately.

**Comment by alolita** [comment]
Hi fabdslv, you are correct. The Kibana RPM Open Distro provides includes Kibana-oss and the OpenDistro plugins for alerting and security. We are working to make the build scripts as well as artifacts for each plugin available. Stay tuned.
