### ISSUE TITLE
Add RSS feed to news page

### ISSUE THREAD

**Issue by MichelZ** [opendistro-for-elasticsearch/community#47]
The [news page](https://opendistro.github.io/for-elasticsearch/news.html) could use an RSS feed.

**Comment by CarlMeadows** [comment]
Thanks for the feedback - we are thinking of converting it to its own blog/Wordpress  (which would have an RSS feed). The current news page was bit of short-term solution :)

**Comment by rhbecker** [comment]
I actually came here (to this repo) just to look for a way to follow progress on this project. Until a subscribe-able news feed is available, do you have a recommendation on the best way to get "high level" updates on progress?

**Comment by jcgraybill** [comment]
Hi, closing this fairly old issue. ATM the best ways to follow the project are to subscribe to notifications from the [Announcements forum topic](https://discuss.opendistrocommunity.dev/c/announcements/5), or to follow the blog on [the Open Distro homepage ](https://opendistro.github.io/for-elasticsearch/). You can also follow @stockholmux [on Twitter](https://twitter.com/stockholmux) for updates.

**Comment by stockholmux** [comment]
To add to @jcgraybill's comment:

* All forum topics have RSS feeds - just add `.rss` to any forum category URL - e.g. `https://discuss.opendistrocommunity.dev/c/announcements/5` -> `https://discuss.opendistrocommunity.dev/c/announcements/5.rss` 

* We do have an RSS feed for releases on the blog: `https://opendistro.github.io/for-elasticsearch/feed/releases.xml` 

We're working on an overhaul of the website, so we'll make sure to add more comprehensive RSS feeds.
