### ISSUE TITLE
Cross-Cluster Replication

### ISSUE THREAD

**Issue by smarch2** [opendistro-for-elasticsearch/community#50]
Cross-Cluster Replication is available now available and production ready in Elastic Search 6.7.0 [(LINK)](https://www.elastic.co/blog/follow-the-leader-an-introduction-to-cross-cluster-replication-in-elasticsearch?ultron=apr-2019&blade=newsletter&hulk=email&mkt_tok=eyJpIjoiWkdaa016SmxOek00TVRGaSIsInQiOiJIS1Y2dHlHXC9ZZFU0V1dVdXlpdmxaNWc4S1l0bWRDemFtUVdaK3RDUllPQjNCelBqZlYyNVNwbHlCeWliblZPZmZIRG9XNktxNFBsNHQ5XC9VQjY2NUI5V3VzTkpMUG5hZjlFY3JnM09GY0ZRV29aTE9JUTBoc29uVlFuVkJJUWhMIn0%3D).

Is there currently anything in the Open Distro Roadmap for a Cross-Cluster Replication feature? If not, can there be?

**Comment by sathomps** [comment]
For those that are currently using ES in a DR/HA setup, I'd be interested in hearing about their implementations without CCR.

**Comment by ronnyle** [comment]
The only DR alternatives without CCR seem to be:
- snapshot & restore from primary to failover site, which involve data loss in a DR scenario
- write to a queue with cross-DC replication capabilities (e.g. Kafka), and connect the queue to both Clusters

Of course, CCR would be preferable to both.

**Comment by CarlMeadows** [comment]
Hi - This is something we have some folks researching and they should be posting a request for comments soon and adding it to the roadmap.

**Comment by pythianLopez** [comment]
Hello, any news what is the current state of this feature? thanks

**Comment by jcgraybill** [comment]
Cross cluster replication is now available! See https://github.com/opendistro-for-elasticsearch/cross-cluster-replication
