### ISSUE TITLE
Tracking upstream elasticsearch?

### ISSUE THREAD

**Issue by unixtastic** [opendistro-for-elasticsearch/community#52]
What's the plan to track upstream releases of elasticsearch? Will your version numbers match theirs with a patch number after it? Is the plan documented somewhere?

This is going to be really important as Elastic release versions with new features and breaking changes frequently.

**Comment by tschutte** [comment]
I'm also curious if there is a plan regarding how closely (temporally) opendistro is will track upstream.  Ie attempt to release 2 weeks after upstream, etc?

**Comment by alolita** [comment]
Hi @tschutte we plan to maintain version currency closely with upstream. 2 weeks for a deployment cadence is a good suggestion.

**Comment by q2dg** [comment]
Well, current Elasticsearch/Kibana upstream version is 7.5.1 but current OpenDistro plugins version is 7.3.2. So...something is failing here
