### ISSUE TITLE
Let kibana use index timezone

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/community#73]
Hi,

There is a configuration on kibana that allows you to choose between using a fix timezone for all users or fix the timezone depending on the timezone of the browser.
I seen some conversations online where this is a limitation since if your data is produced across multiple timezones there is no real way to graph it other than creating one index per timezone.
I would like to open de discussion and ask it as a possible enhancement on the tool add the ability to let kibana just use the timezone on the field of the index.

What do you think of this?

**Comment by bbarani** [comment]
@mporracindie , Elasticsearch stores the date in UTC internally, and Kibana will use your local timezone to display those UTC dates.  Do you still need any other inputs on this issue?
