### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by narendralussspacetech** [opendistro-for-elasticsearch/community#74]
Hello,

I'm trying to install openDistro at my local system Ubuntu 16.04 followed by instruction from [here](https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/).

And getting below error:
```
apt install opendistroforelasticsearch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libvulkan1 libvulkan1:i386
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  opendistroforelasticsearch
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
1 not fully installed or removed.
Need to get 702 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 opendistroforelasticsearch amd64 0.9.0-1 [702 B]
Fetched 702 B in 1s (576 B/s)                      
Selecting previously unselected package opendistroforelasticsearch.
(Reading database ... 612923 files and directories currently installed.)
Preparing to unpack .../opendistroforelasticsearch_0.9.0-1_amd64.deb ...
Unpacking opendistroforelasticsearch (0.9.0-1) ...
Setting up elasticsearch-oss (6.7.1) ...
/usr/share/elasticsearch/bin/elasticsearch-env: line 71: /etc/default/elasticsearch: No such file or directory
dpkg: error processing package elasticsearch-oss (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of opendistroforelasticsearch:
 opendistroforelasticsearch depends on elasticsearch-oss (= 6.7.1); however:
  Package elasticsearch-oss is not configured yet.

dpkg: error processing package opendistroforelasticsearch (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 elasticsearch-oss
 opendistroforelasticsearch
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Please help!

**Comment by ulab** [comment]
Did you do step 4 to install elasticsearch-oss first?

> wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.7.1.deb
> sudo dpkg  -i elasticsearch-oss-6.7.1.deb

Please note that the issues section is not meant for support questions, but to report bugs. You'd probably get more detailed help if you'd join the community forums: https://discuss.opendistrocommunity.dev/

**Comment by narendralussspacetech** [comment]
yes, i'm doing it in the same sequence

**Comment by narendralussspacetech** [comment]
I resolved this error by uninstalling and install it again. but now, I'm facing some issue while start elasticsearch service using Linux command line `sudo systemctl status elasticsearch.service`.

Service status saying: 
`elasticsearch[31315]: java.security.policy: error adding Entry: elasticsearch[31315]: java.net.MalformedURLException: unknown protocol: jrt systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE`

In log, showing something like `java.io.FileNotFoundException: /usr/share/elasticsearch/lib/tools.jar (No such file or directory)`

**Comment by aetter** [comment]
Hi @narendralussspacetech, typically this only occurs if you're running Java 8. On Ubuntu, we require Java 11. Can you verify that you have Java 11 installed and that JAVA_HOME is set properly?
