### ISSUE TITLE
Does opendistro support ILM 

### ISSUE THREAD

**Issue by r00t9** [opendistro-for-elasticsearch/community#77]
Hello :)

Opendistro support ILM - (Index Lifecycle Management)?

I tried _ilm/status and _ilm_start but i get error, i think ILM work with out X-PACK

opendistro version:     "number" : "6.7.1",

Cheers :)

**Comment by aetter** [comment]
Hi @r00t9, index lifecycle management is part of the "default" distribution of Elasticsearch, not the open source version. We've started work on an open source plugin that should address similar use cases. You can follow along here: https://github.com/opendistro-for-elasticsearch/index-management

**Comment by r00t9** [comment]
Thanks a lot @aetter  :)
