### ISSUE TITLE
Error when indexing new data

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/community#79]
Hi, im getting this error when trying to index into an existing index. Any ideas what could be happening?

`[2019-06-13T15:27:03,585][INFO ][o.e.m.j.JvmGcMonitorService] [xTpc1RF] [gc][22863] overhead, spent [301ms] collecting in the last [1s]`

**Comment by alolita** [comment]
@mporracindie - were you able to solve this issue of reusing an existing index?

**Comment by mporracindie** [comment]
Sincerely I can't really recall how we solve this :(
