### ISSUE TITLE
Autocomplete on discovery tab not working

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/community#86]
Hi,

I'm having issues getting to work the autocomplete for fields when typing into the discovery filter field. Any ideas why this could be happening?

<img width="1110" alt="Screen Shot 2019-06-19 at 09 47 02" src="https://user-images.githubusercontent.com/42622776/59766847-684ab200-9277-11e9-9106-5defa474578c.png">

**Comment by mihirsoni** [comment]
@mporracindie  This feature is part of x-pack and thus it is not provided by open source kibana.

>Kibana Query Languageedit
In Kibana 6.3, we introduced a number of exciting experimental query language enhancements. These features are now available by default in 7.0. Out of the box, Kibana’s query language now includes scripted field support and a simplified, easier to use syntax. **If you have a Basic license or above, autocomplete functionality will also be enabled.**
