### ISSUE TITLE
Tag/Rename patterns

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/community#95]
Hi,

I'm not sure if this is the right place to ask but it would be great if you could name an index pattern and in another field define which indexes it takes into consideration. 

**Is there a use case?**
Imagine you have an index per week called myindex-<week number> (Example: myindex-52) so your pattern would be myindex* or myindex-*.
Now if you have two or more different time dates inside each you would like to sort this on you dashboards you would need to keep creating patterns like: 
myindex*
myindex**
myindex***

In order to still collect data from all your indexes and choose a different time date as a reference on each one. And even if this works and you would be able to use them it becomes really annoying having to memorize how many * has each time date or just go back and forth looking into it.

**Solution?**
If it's possible it would be great to be able to create the index pattern called: myindex-datefield that behind works as myindex** and at the same time have myindex-anotherfield that behind works as myindex*.
This would be just a mask in order to be able to differentiate them easily when creating dashboards/visualizations.

**Comment by jcgraybill** [comment]
Closing this for now. @mporracindie if you're still looking for help, feel free to post a question to the [Open Distro forum](https://discuss.opendistrocommunity.dev/).
