### ISSUE TITLE
Downgrade kibana version from 7.0.1 to 6.7.1

### ISSUE THREAD

**Issue by AmarnathVibhute** [opendistro-for-elasticsearch/community#98]
Hello,
I am facing issue with version compatibility between Open distro Elasticsearch 6.7.1 and Kibana 7.0.1. I am not sure how the Kibana got upgraded from 6.7.1 to 7.0.1 and **I do not want** to upgrade (as there is lot of indices with good amount of data I cant loose) the Elasticsearch to 7.0.1. 

Please help me with instructions to **downgrade** the Kibana version **7.0.1 to 6.7.1**

I tried _sudo yum downgrade opendistroforelasticsearch-kibana_ to see if I can get earlier version of Kibana, but it takes me to version **1.0.0-1** 

Thanks,
Amarnath

**Comment by aetter** [comment]
Hi @AmarnathVibhute, try specifying a specific version

```
sudo yum downgrade opendistroforelasticsearch-kibana-0.9.0
```

Kibana stores all its settings in some indices that might or might not have been altered during the upgrade/on Kibana 7.x startup, but give it a shot.
